/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package emir_turkmen_hw1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.Arrays;
import java.util.ArrayList;

class AppTest {
    @Test void whenNumberFoundinArrayList(){
        Integer [] a = new Integer[]{1,2,3,4,5,6,7};
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(a));
        assertTrue(App.searchNumberBetweenIndexesiandj(arr, 1, 4, 3));
    }
    @Test void whenNumberNotFoundinArrayList(){
        Integer [] a = new Integer[]{1,2,3,4,5,6,7};
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(a));
        assertFalse(App.searchNumberBetweenIndexesiandj(arr, 1, 4, 10));
    }
    @Test void whenArrayListisEmpty(){
        Integer [] a = new Integer[]{};
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(a));
        assertFalse(App.searchNumberBetweenIndexesiandj(arr, 1, 4, 3));
    }
    @Test void whenIndexiBiggerThanIndexj(){
        Integer [] a = new Integer[]{1,2,3,4,5,6,7};
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(a));
        assertFalse(App.searchNumberBetweenIndexesiandj(arr, 4, 2, 3));
    }
    @Test void whenIndexiLowerThanZero(){
        Integer [] a = new Integer[]{1,2,3,4,5,6,7};
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(a));
        assertFalse(App.searchNumberBetweenIndexesiandj(arr, -1, 4, 3));
    }
    @Test void whenIndexjEqualsorBiggerThanSize(){
        Integer [] a = new Integer[]{1,2,3,4,5,6,7};
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(a));
        assertFalse(App.searchNumberBetweenIndexesiandj(arr, 1, 8, 3));
    }
}