/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package emir_turkmen_hw1;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean searchNumberBetweenIndexesiandj(ArrayList<Integer> arr, Integer i, Integer j, Integer number){
        if(arr.size()==0 || i<0 || j>arr.size()-1 || i>j){
            return false;
        }
        for(int x = i; x<=j;x++)
            if(arr.get(x)== number)
                return true;
        return false;
    }
}